-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 21:28:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eshop` DEFAULT CHARACTER SET utf8 ;
USE `eshop` ;

-- -----------------------------------------------------
-- Table `eshop`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eshop`.`items` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `price` FLOAT NULL,
  `image` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eshop`.`sessions` (
  `id` INT NOT NULL,
  `ip_address` VARCHAR(45) NULL,
  `timestamp` INT NULL,
  `data` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eshop`.`categories` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eshop`.`users` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` TEXT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `level` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eshop`.`order` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `address` TEXT NULL,
  `address_e` TEXT NULL,
  `country` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `state` TEXT NULL,
  `payment` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`order_has_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eshop`.`order_has_items` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `order_id` INT NOT NULL,
  `items_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eshop`.`pages` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` BLOB NULL,
  `created` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
